fruit_list=list(("Apple","Banana","Chikoo","damson","Mango"))
print("\n Fruit List is:=",fruit_list)
print()
#a=input("\nEnter element location which you need to display:")
#print("\nElement is:="+fruit_list[int(a)]);
#b=input("\n Enter element to remove:")
#fruit_list.remove(b)
#print("Element is Removed Ten List is:")
#print(fruit_list)
print("\n Length is:=",+len(fruit_list))

F_list=fruit_list.copy()
print("\n F_list is:=",F_list)
fruit_list.extend(F_list)
print("\n List after Extension:=",fruit_list)
F_list.reverse()
print("\n List After Reverse:=",F_list)
F_list.sort()
print("List After Sorting:=",F_list)
